// <auto-generated />
using System;
using ElarosApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElarosApp.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20210111152552_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ElarosApp.Models.Activities", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivitiesId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ElarosApp.Models.Anxiety", b =>
                {
                    b.Property<int>("AnxietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnxietyId");

                    b.ToTable("Anxiety");
                });

            modelBuilder.Entity("ElarosApp.Models.Cognition", b =>
                {
                    b.Property<int>("CognitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("DifficultyConcentrating")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ShortTermMemoryEffected")
                        .HasColumnType("bit");

                    b.HasKey("CognitionId");

                    b.ToTable("Cognition");
                });

            modelBuilder.Entity("ElarosApp.Models.Communication", b =>
                {
                    b.Property<int>("CommunicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("DifficultyCommunicating")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommunicationId");

                    b.ToTable("Communication");
                });

            modelBuilder.Entity("ElarosApp.Models.Consumption", b =>
                {
                    b.Property<int>("ConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("DifficultySwallowing")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WeightlossConcern")
                        .HasColumnType("bit");

                    b.HasKey("ConsumptionId");

                    b.ToTable("Consumption");
                });

            modelBuilder.Entity("ElarosApp.Models.Continence", b =>
                {
                    b.Property<int>("ContinenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("BladderProblems")
                        .HasColumnType("bit");

                    b.Property<bool?>("BowelProblems")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinenceId");

                    b.ToTable("Continence");
                });

            modelBuilder.Entity("ElarosApp.Models.Depression", b =>
                {
                    b.Property<int>("DepressionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepressionId");

                    b.ToTable("Depression");
                });

            modelBuilder.Entity("ElarosApp.Models.Fatigue", b =>
                {
                    b.Property<int>("FatigueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FatigueId");

                    b.ToTable("Fatigue");
                });

            modelBuilder.Entity("ElarosApp.Models.Mobility", b =>
                {
                    b.Property<int>("MobilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobilityId");

                    b.ToTable("Mobility");
                });

            modelBuilder.Entity("ElarosApp.Models.Pain", b =>
                {
                    b.Property<int>("PainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("NewPain")
                        .HasColumnType("bit");

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PainId");

                    b.ToTable("Pain");
                });

            modelBuilder.Entity("ElarosApp.Models.PatientModel", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CurrentQuestionQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("ReferalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("CurrentQuestionQuestionId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ElarosApp.Models.PersonalCare", b =>
                {
                    b.Property<int>("PersonalCareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalCareId");

                    b.ToTable("PersonalCare");
                });

            modelBuilder.Entity("ElarosApp.Models.Ptsd", b =>
                {
                    b.Property<int>("PtsdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("SelfharmThoughts")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ThoughtOrFeelingAvoidance")
                        .HasColumnType("bit");

                    b.Property<bool?>("UnpleasantDreams")
                        .HasColumnType("bit");

                    b.Property<bool?>("UnwantedMemoriesWhilstAwake")
                        .HasColumnType("bit");

                    b.HasKey("PtsdId");

                    b.ToTable("Ptsd");
                });

            modelBuilder.Entity("ElarosApp.Models.QuestionModel", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("AnxietyId")
                        .HasColumnType("int");

                    b.Property<int>("CognitionId")
                        .HasColumnType("int");

                    b.Property<int>("CommunicationId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumptionId")
                        .HasColumnType("int");

                    b.Property<int>("ContinenceId")
                        .HasColumnType("int");

                    b.Property<int>("DepressionId")
                        .HasColumnType("int");

                    b.Property<int>("FatigueId")
                        .HasColumnType("int");

                    b.Property<int>("MobilityId")
                        .HasColumnType("int");

                    b.Property<int>("PainId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalCareId")
                        .HasColumnType("int");

                    b.Property<int>("PtsdId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocialRoleId")
                        .HasColumnType("int");

                    b.Property<int>("VoiceId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("ActivitiesId");

                    b.HasIndex("AnxietyId");

                    b.HasIndex("CognitionId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("ConsumptionId");

                    b.HasIndex("ContinenceId");

                    b.HasIndex("DepressionId");

                    b.HasIndex("FatigueId");

                    b.HasIndex("MobilityId");

                    b.HasIndex("PainId");

                    b.HasIndex("PersonalCareId");

                    b.HasIndex("PtsdId");

                    b.HasIndex("SocialRoleId");

                    b.HasIndex("VoiceId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ElarosApp.Models.SocialRole", b =>
                {
                    b.Property<int>("SocialRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Postcovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precovid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialRoleId");

                    b.ToTable("SocialRole");
                });

            modelBuilder.Entity("ElarosApp.Models.Voice", b =>
                {
                    b.Property<int>("VoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("NoiseyBreathing")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SoreThroat")
                        .HasColumnType("bit");

                    b.Property<bool?>("VoiceChange")
                        .HasColumnType("bit");

                    b.HasKey("VoiceId");

                    b.ToTable("Voice");
                });

            modelBuilder.Entity("ElarosApp.Models.PatientModel", b =>
                {
                    b.HasOne("ElarosApp.Models.QuestionModel", "CurrentQuestion")
                        .WithMany()
                        .HasForeignKey("CurrentQuestionQuestionId");

                    b.Navigation("CurrentQuestion");
                });

            modelBuilder.Entity("ElarosApp.Models.QuestionModel", b =>
                {
                    b.HasOne("ElarosApp.Models.Activities", "Activities")
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Anxiety", "Anxiety")
                        .WithMany()
                        .HasForeignKey("AnxietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Cognition", "Cognition")
                        .WithMany()
                        .HasForeignKey("CognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Consumption", "Consumption")
                        .WithMany()
                        .HasForeignKey("ConsumptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Continence", "Continence")
                        .WithMany()
                        .HasForeignKey("ContinenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Depression", "Depression")
                        .WithMany()
                        .HasForeignKey("DepressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Fatigue", "Fatigue")
                        .WithMany()
                        .HasForeignKey("FatigueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Mobility", "Mobility")
                        .WithMany()
                        .HasForeignKey("MobilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Pain", "Pain")
                        .WithMany()
                        .HasForeignKey("PainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.PersonalCare", "PersonalCare")
                        .WithMany()
                        .HasForeignKey("PersonalCareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Ptsd", "Ptsd")
                        .WithMany()
                        .HasForeignKey("PtsdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.SocialRole", "SocialRole")
                        .WithMany()
                        .HasForeignKey("SocialRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarosApp.Models.Voice", "Voice")
                        .WithMany()
                        .HasForeignKey("VoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activities");

                    b.Navigation("Anxiety");

                    b.Navigation("Cognition");

                    b.Navigation("Communication");

                    b.Navigation("Consumption");

                    b.Navigation("Continence");

                    b.Navigation("Depression");

                    b.Navigation("Fatigue");

                    b.Navigation("Mobility");

                    b.Navigation("Pain");

                    b.Navigation("PersonalCare");

                    b.Navigation("Ptsd");

                    b.Navigation("SocialRole");

                    b.Navigation("Voice");
                });
#pragma warning restore 612, 618
        }
    }
}
